### ISSUE TITLE
upgrade handler is missing for v1.13.0 upgrade plan

### ISSUE THREAD

**Issue by bert2002** [InjectiveLabs/testnet-config#5]
Hi,
it seems the latest `1.13.2` release is not working correctly.

```
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | 12:50AM ERR Error dialing peer err="dial tcp 54.69.206.239:26656: i/o timeout" module=p2p
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | 12:50AM ERR Error dialing peer err="dial tcp 35.237.175.17:26656: i/o timeout" module=p2p
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | 12:50AM ERR error in proxyAppConn.FinalizeBlock err="wrong app version 0, upgrade handler is missing for v1.13.0 upgrade plan" module=state
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | panic: Failed to process committed block (37307639:25A78DA4D9DB1F20FDB0BC3A2631310A9476462F010FD7507FE68D93C25CCA49): wrong app version 0, upgrade handler is missing for v1.13.0 upgrade plan
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  |
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | goroutine 428 [running]:
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc002b24200, 0x0)
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.10-inj-1/blocksync/reactor.go:552 +0x1946
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart.func1()
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.10-inj-1/blocksync/reactor.go:142 +0x54
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  | created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
Jul 19 00:50:23 inj-1[41718]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.10-inj-1/blocksync/reactor.go:140 +0x8b
Jul 19 00:50:24 inj-1[41718]: injective-cosmos-1 exited with code 0
```

Image is `public.ecr.aws/l9h3g6c6/injective-core:v1.13.2-testnet`

Thanks,
bert

**Comment by Ri-go** [comment]
You need to upgrade using 1.13.0 first, then progress to 1.13.1 then eventually 1.13.2 every halt.
Unlike with mainnet releases, testnet only loosely follows semantic versioning. so the difference between 1.13.x releases aren't necessarily patches.

**Comment by bert2002** [comment]
I tried updating to `1.13.1` first, but I am only getting a lot of `i/o timeout` on the peers.
On `1.13.0` I see this
```
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | 9:23AM ERR Error dialing peer err="dial tcp 18.201.228.229:26656: i/o timeout" module=p2p
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | 9:23AM ERR Error dialing peer err="dial tcp 35.231.159.65:26656: i/o timeout" module=p2p
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | panic: Int64() out of bound
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | goroutine 392 [running]:
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | cosmossdk.io/math.Int.Int64({0x0?})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/cosmossdk.io/math@v1.3.0/int.go:206 +0x7b
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/types.TokensToConsensusPower({0x0?}, {0x0?})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/types/staking.go:29 +0x1d
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/types.Validator.PotentialConsensusPower(...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/types/validator.go:363
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/types.Validator.ConsensusPower(...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/types/validator.go:355
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/types.ValidatorsByVotingPower.Less({0xc0002b4a88, 0x4, 0x1?}, 0x18?, 0x8?, {0xc0dbf9e188?})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/types/validator.go:127 +0x145
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/types.NewHistoricalInfo.func1(0xc0ff5e2a38?, 0xc0dbc289a0?)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/types/historical_info.go:22 +0x2f
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | sort.insertionSort_func({0xc0dbf9e268?, 0xc00228f410?}, 0x0, 0x4)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /usr/local/go/src/sort/zsortfunc.go:12 +0xa7
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | sort.stable_func({0xc0dbf9e268?, 0xc00228f410?}, 0x4)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /usr/local/go/src/sort/zsortfunc.go:343 +0x75
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | sort.SliceStable({0x4ee4500?, 0xc0ff5e2a38?}, 0xc0dbf9e268)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /usr/local/go/src/sort/slice.go:44 +0xb0
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/types.NewHistoricalInfo({{0x0, 0x0}, {0xc001bec3d0, 0xd}, 0x239ed3b, {0x141f6bca, 0xede2b31b6, 0x0}, {{0x0, 0x0, ...}, ...}, ...}, ...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/types/historical_info.go:21 +0xf9
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.TrackHistoricalInfo({{0x686ee80, 0xc001c1c4e8}, {0x68d77e0, 0xc0019ecb60}, {0x68bfe18, 0xc0027b1900}, {0x7f25e83448c0, 0xc0014dd688}, {0x68d7850, 0xc001e08d68}, ...}, ...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/keeper/historical_info.go:125 +0x4de
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking/keeper.(*Keeper).BeginBlocker(0x378?, {0x68b51c0?, 0xc0022be388?})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/keeper/abci.go:16 +0x13e
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/x/staking.AppModule.BeginBlock(...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/x/staking/module.go:181
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x68b5230, 0xc016501c20}, {0x68d8260, 0xc128dffb40}, {{0x0, 0x0}, {0xc001bec3d0, 0xd}, 0x239ed3b, ...}, ...})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/types/module/module.go:779 +0x188
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/InjectiveLabs/injective-core/injective-chain/app.(*InjectiveApp).BeginBlocker(_, {{0x68b5230, 0xc016501c20}, {0x68d8260, 0xc128dffb40}, {{0x0, 0x0}, {0xc001bec3d0, 0xd}, 0x239ed3b, ...}, ...})
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /src/injective-chain/app/app.go:568 +0x318
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).beginBlock(0xc002700008, 0xc0dbbd6f00?)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/baseapp/baseapp.go:744 +0x176
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).internalFinalizeBlock(0xc002700008, {0x68b50a8, 0x918b620}, 0xc0dbbd6f00)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/baseapp/abci.go:780 +0x115e
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).FinalizeBlock(0xc002700008, 0xc0dbbd6f00)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/baseapp/abci.go:904 +0x16e
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.FinalizeBlock(...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.50.7-0.20240715151413-9c09fcb833cd/server/cmt_abci.go:44
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0x68d9190?, {0x68b5310?, 0x918b620?}, 0x7f25699d6e88?)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/abci/client/local_client.go:185 +0xcd
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc006d1e960, {0x68b5310, 0x918b620}, 0xc0dbbd6f00)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/proxy/app_conn.go:104 +0x170
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_, {{{0xb, 0x0}, {0xc0e4e249d8, 0x7}}, {0xc0e4e24a00, 0xd}, 0x26aa60, 0x239ed3a, {{0xc0030bf160, ...}, ...}, ...}, ...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/state/execution.go:232 +0x525
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(...)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/state/execution.go:207
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc0e4e621e0, 0x0)
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/blocksync/reactor.go:530 +0x1492
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart.func1()
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/blocksync/reactor.go:132 +0x54
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  | created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
Jul 19 09:23:13 inj-1 injective[48634]: injective-cosmos-1  |         /go/pkg/mod/github.com/!injective!labs/cometbft@v0.38.9-0.20240709140635-a708e04e3d90/blocksync/reactor.go:130 +0x8b
```
and `1.12.10` is
```
injective-cosmos-1  | failed to load latest version: failed to load store: no versions found while trying to load 37350714
```

Anything looks familiar?

**Comment by Ri-go** [comment]
We will be releasing an upgrade guide to the upgrading process easier and more straight forward. Will update you ASAP

**Comment by bangjelkoski** [comment]
https://injective.notion.site/Testnet-v1-13-X-Upgrade-Guide-c2e4f24576804b279fbf997f79312bdc here is the upgrade gudie @bert2002

**Comment by baabeetaa** [comment]
the upgrade guide works, thanks @bangjelkoski
